server:
  port: 8501

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/

spring:
  cloud:
    cassandra:
      contact:
        point: localhost
      port: 9042
      username: cassandra
      password: cassandra
      keyspace:
        name: springcloud
  application:
    name: account-service