server:
  port: 8501

spring:
  cloud:
    cassandra:
      contact:
        point: localhost
      port: 9042
      username: cassandra
      password: cassandra
      keyspace:
        name: springcloud
